In [1]:
import pennylane as qp
import numpy as np
import matplotlib.pyplot as plt

dev = qp.device("default.qubit", wires=1)

In [2]:
def decomposed_rot(phi, theta, omega):
    qp.RZ(phi, wires=0)
    qp.RY(theta, wires=0)
    qp.RZ(omega, wires=0)

In [30]:
# ADJUST THE VALUES OF PHI, THETA, AND OMEGA
phi, theta, omega = np.pi/2, np.pi/2, np.pi/2

In [39]:
@qp.qnode(dev)
def hadamard_with_rz_rx():
    qp.RZ(phi, wires=0)
    qp.RX(theta, wires=0)
    qp.RZ(omega, wires=0)
    return qp.state()

In [40]:
hadamard_with_rz_rx()

array([ 2.29934717e-17-0.70710678j, -2.29934717e-17-0.70710678j])

In [41]:
@qp.qnode(dev)
def convert_to_rz_rx():
    # IMPLEMENT THE CIRCUIT IN THE PICTURE USING ONLY RZ AND RX

    # H
    qp.RZ(np.pi/2, wires=0)
    qp.RX(np.pi/2, wires=0)
    qp.RZ(np.pi/2, wires=0)

    # S
    qp.RZ(np.pi/2, wires=0)

    # adjoint(T)
    qp.RZ(-np.pi/4, wires=0)

    # Y
    qp.RZ(np.pi/2, wires=0)
    qp.RX(np.pi, wires=0)
    qp.RZ(-np.pi/2, wires=0)

    return qp.state()

In [42]:
convert_to_rz_rx()

array([0.27059805-0.65328148j, 0.27059805+0.65328148j])

In [47]:
@qp.qnode(dev)
def unitary_with_h_and_t():
    # APPLY ONLY H AND T TO PRODUCE A CIRCUIT THAT EFFECTS THE GIVEN MATRIX
    qp.Hadamard(wires=0)
    qp.T(wires=0)
    qp.Hadamard(wires=0)
    qp.T(wires=0)
    qp.T(wires=0)
    qp.Hadamard(wires=0)

    return qp.state()

In [48]:
unitary_with_h_and_t()

array([0.85355339+0.35355339j, 0.35355339+0.14644661j])